import { MenuItem } from './types';

export const menuItems: MenuItem[] = [
  {
    id: 'coffee-espresso',
    name: 'Espresso',
    category: 'coffee',
    price: 3.50,
    description: 'Rich and bold single shot espresso with a perfect crema.',
    image: '/images/espresso.jpg',
    customizations: ['Extra Shot', 'Decaf'],
  },
  {
    id: 'coffee-latte',
    name: 'Caffè Latte',
    category: 'coffee',
    price: 4.50,
    description: 'Smooth espresso with steamed milk and light foam.',
    image: '/images/latte.jpg',
    customizations: ['Extra Shot', 'Oat Milk', 'Almond Milk', 'Vanilla Syrup'],
  },
  {
    id: 'coffee-cappuccino',
    name: 'Cappuccino',
    category: 'coffee',
    price: 4.50,
    description: 'Classic Italian coffee with equal parts espresso, steamed milk, and foam.',
    image: '/images/cappuccino.jpg',
    customizations: ['Extra Shot', 'Oat Milk', 'Cinnamon Dust'],
  },
  {
    id: 'coffee-americano',
    name: 'Americano',
    category: 'coffee',
    price: 3.75,
    description: 'Espresso diluted with hot water for a smooth, rich flavor.',
    image: '/images/americano.jpg',
    customizations: ['Extra Shot', 'Iced'],
  },
  {
    id: 'coffee-mocha',
    name: 'Mocha',
    category: 'coffee',
    price: 5.25,
    description: 'Espresso with chocolate and steamed milk topped with whipped cream.',
    image: '/images/mocha.jpg',
    customizations: ['Extra Shot', 'Oat Milk', 'No Whip'],
  },

  {
    id: 'bakery-croissant',
    name: 'Butter Croissant',
    category: 'bakery',
    price: 3.25,
    description: 'Flaky, buttery French pastry baked fresh every morning.',
    image: '/images/croissant.jpg',
    customizations: ['Warmed'],
  },
  {
    id: 'bakery-muffin',
    name: 'Blueberry Muffin',
    category: 'bakery',
    price: 3.50,
    description: 'Moist muffin loaded with fresh blueberries.',
    image: '/images/muffin.jpg',
    customizations: ['Warmed'],
  },
  {
    id: 'bakery-danish',
    name: 'Apple Danish',
    category: 'bakery',
    price: 3.75,
    description: 'Sweet pastry filled with spiced apple compote and drizzled with icing.',
    image: '/images/danish.jpg',
    customizations: ['Warmed'],
  },
  {
    id: 'bakery-bagel',
    name: 'Everything Bagel',
    category: 'bakery',
    price: 2.75,
    description: 'Classic bagel with sesame, poppy, onion, and garlic.',
    image: '/images/bagel.jpg',
    customizations: ['Cream Cheese', 'Butter', 'Toasted'],
  },
  {
    id: 'bakery-scone',
    name: 'Cranberry Scone',
    category: 'bakery',
    price: 3.50,
    description: 'Tender British-style scone with sweet cranberries.',
    image: '/images/scone.jpg',
    customizations: ['Warmed', 'Clotted Cream'],
  },

  {
    id: 'cake-cheesecake',
    name: 'New York Cheesecake',
    category: 'cake',
    price: 6.50,
    description: 'Creamy classic cheesecake with graham cracker crust.',
    image: '/images/cheesecake.jpg',
    customizations: ['Strawberry Topping', 'Chocolate Drizzle'],
  },
  {
    id: 'cake-tiramisu',
    name: 'Tiramisu',
    category: 'cake',
    price: 7.00,
    description: 'Italian dessert with espresso-soaked ladyfingers and mascarpone cream.',
    image: '/images/tiramisu.jpg',
    customizations: [],
  },
  {
    id: 'cake-brownie',
    name: 'Fudge Brownie',
    category: 'cake',
    price: 4.50,
    description: 'Dense chocolate brownie with a crisp top and gooey center.',
    image: '/images/brownie.jpg',
    customizations: ['Warmed', 'Ice Cream'],
  },
  {
    id: 'cake-carrot',
    name: 'Carrot Cake',
    category: 'cake',
    price: 5.75,
    description: 'Spiced carrot cake layered with cream cheese frosting.',
    image: '/images/carrot-cake.jpg',
    customizations: [],
  },
  {
    id: 'cake-eclair',
    name: 'Chocolate Éclair',
    category: 'cake',
    price: 4.75,
    description: 'Choux pastry filled with vanilla cream and topped with chocolate.',
    image: '/images/eclair.jpg',
    customizations: [],
  },

  {
    id: 'food-sandwich',
    name: 'Turkey Club',
    category: 'food',
    price: 9.50,
    description: 'Triple-decker sandwich with turkey, bacon, lettuce, and tomato.',
    image: '/images/sandwich.jpg',
    customizations: ['No Mayo', 'Gluten-Free Bread'],
  },
  {
    id: 'food-salad',
    name: 'Caesar Salad',
    category: 'food',
    price: 8.50,
    description: 'Crisp romaine with parmesan, croutons, and house Caesar dressing.',
    image: '/images/salad.jpg',
    customizations: ['Add Chicken', 'Dressing on Side'],
  },
  {
    id: 'food-quiche',
    name: 'Spinach Quiche',
    category: 'food',
    price: 7.25,
    description: 'French-style quiche with fresh spinach and gruyère cheese.',
    image: '/images/quiche.jpg',
    customizations: ['Side Salad'],
  },
  {
    id: 'food-soup',
    name: 'Tomato Basil Soup',
    category: 'food',
    price: 5.50,
    description: 'Creamy tomato soup with fresh basil and a hint of garlic.',
    image: '/images/soup.jpg',
    customizations: ['Bread Bowl', 'Crackers'],
  },
  {
    id: 'food-wrap',
    name: 'Chicken Caesar Wrap',
    category: 'food',
    price: 8.75,
    description: 'Grilled chicken with romaine and Caesar dressing in a flour tortilla.',
    image: '/images/wrap.jpg',
    customizations: ['Gluten-Free Wrap', 'Extra Dressing'],
  },
];

export const getMenuByCategory = (category: string): MenuItem[] => {
  return menuItems.filter((item) => item.category === category);
};

export const getMenuItemById = (id: string): MenuItem | undefined => {
  return menuItems.find((item) => item.id === id);
};

export const categories = [
  { id: 'coffee', name: 'Coffee', icon: 'Coffee' },
  { id: 'bakery', name: 'Bakery', icon: 'Croissant' },
  { id: 'cake', name: 'Cake', icon: 'Cake' },
  { id: 'food', name: 'Food', icon: 'UtensilsCrossed' },
];
