import { MenuItem } from './types';

export const menuItems: MenuItem[] = [
  {
    id: 'coffee-espresso',
    name: 'Espresso',
    category: 'coffee',
    price: 3.50,
    description: 'Rich and bold single shot espresso with a perfect crema.',
    image: '/images/coffee/coffee-espresso.jpg',
    customizations: ['Extra Shot', 'Decaf'],
  },
  {
    id: 'coffee-latte',
    name: 'Caffè Latte',
    category: 'coffee',
    price: 4.50,
    description: 'Smooth espresso with steamed milk and light foam.',
    image: '/images/coffee/coffee-latte.jpg',
    customizations: ['Extra Shot', 'Oat Milk', 'Almond Milk', 'Vanilla Syrup'],
  },
  {
    id: 'coffee-cappuccino',
    name: 'Cappuccino',
    category: 'coffee',
    price: 4.50,
    description: 'Classic Italian coffee with equal parts espresso, steamed milk, and foam.',
    image: '/images/coffee/coffee-cappuccino.jpg',
    customizations: ['Extra Shot', 'Oat Milk', 'Cinnamon Dust'],
  },
  {
    id: 'coffee-americano',
    name: 'Americano',
    category: 'coffee',
    price: 3.75,
    description: 'Espresso diluted with hot water for a smooth, rich flavor.',
    image: '/images/coffee/coffee-americano.png',
    customizations: ['Extra Shot', 'Iced'],
  },
  {
    id: 'coffee-mocha',
    name: 'Mocha',
    category: 'coffee',
    price: 5.25,
    description: 'Espresso with chocolate and steamed milk topped with whipped cream.',
    image: '/images/coffee/coffee-mocha.png',
    customizations: ['Extra Shot', 'Oat Milk', 'No Whip'],
  },

  {
    id: 'bakery-croissant',
    name: 'Butter Croissant',
    category: 'bakery',
    price: 3.25,
    description: 'Flaky, buttery French pastry baked fresh every morning.',
    image: '/images/bakery/bakery-croissant.png',
    customizations: ['Warmed'],
  },
  {
    id: 'bakery-muffin',
    name: 'Blueberry Muffin',
    category: 'bakery',
    price: 3.50,
    description: 'Moist muffin loaded with fresh blueberries.',
    image: '/images/bakery/bakery-muffin.png',
    customizations: ['Warmed'],
  },
  {
    id: 'bakery-danish',
    name: 'Apple Danish',
    category: 'bakery',
    price: 3.75,
    description: 'Sweet pastry filled with spiced apple compote and drizzled with icing.',
    image: '/images/bakery/bakery-danish.png',
    customizations: ['Warmed'],
  },
  {
    id: 'bakery-bagel',
    name: 'Everything Bagel',
    category: 'bakery',
    price: 2.75,
    description: 'Classic bagel with sesame, poppy, onion, and garlic.',
    image: '/images/bakery/bakery-bagel.png',
    customizations: ['Cream Cheese', 'Butter', 'Toasted'],
  },
  {
    id: 'bakery-scone',
    name: 'Cranberry Scone',
    category: 'bakery',
    price: 3.50,
    description: 'Tender British-style scone with sweet cranberries.',
    image: '/images/bakery/bakery-scone.png',
    customizations: ['Warmed', 'Clotted Cream'],
  },

  {
    id: 'cake-cheesecake',
    name: 'New York Cheesecake',
    category: 'cake',
    price: 6.50,
    description: 'Creamy classic cheesecake with graham cracker crust.',
    image: '/images/cake/cake-cheesecake.png',
    customizations: ['Strawberry Topping', 'Chocolate Drizzle'],
  },
  {
    id: 'cake-tiramisu',
    name: 'Tiramisu',
    category: 'cake',
    price: 7.00,
    description: 'Italian dessert with espresso-soaked ladyfingers and mascarpone cream.',
    image: '/images/cake/cake-tiramisu.png',
    customizations: [],
  },
  {
    id: 'cake-brownie',
    name: 'Fudge Brownie',
    category: 'cake',
    price: 4.50,
    description: 'Dense chocolate brownie with a crisp top and gooey center.',
    image: '/images/cake/cake-brownie.png',
    customizations: ['Warmed', 'Ice Cream'],
  },
  {
    id: 'cake-carrot',
    name: 'Carrot Cake',
    category: 'cake',
    price: 5.75,
    description: 'Spiced carrot cake layered with cream cheese frosting.',
    image: '/images/cake/cake-carrot.png',
    customizations: [],
  },
  {
    id: 'cake-eclair',
    name: 'Chocolate Éclair',
    category: 'cake',
    price: 4.75,
    description: 'Choux pastry filled with vanilla cream and topped with chocolate.',
    image: '/images/cake/cake-eclair.png',
    customizations: [],
  },

  {
    id: 'food-sandwich',
    name: 'Turkey Club',
    category: 'food',
    price: 9.50,
    description: 'Triple-decker sandwich with turkey, bacon, lettuce, and tomato.',
    image: '/images/food/food-sandwich.png',
    customizations: ['No Mayo', 'Gluten-Free Bread'],
  },
  {
    id: 'food-salad',
    name: 'Caesar Salad',
    category: 'food',
    price: 8.50,
    description: 'Crisp romaine with parmesan, croutons, and house Caesar dressing.',
    image: '/images/food/food-salad.png',
    customizations: ['Add Chicken', 'Dressing on Side'],
  },
  {
    id: 'food-quiche',
    name: 'Spinach Quiche',
    category: 'food',
    price: 7.25,
    description: 'French-style quiche with fresh spinach and gruyère cheese.',
    image: '/images/food/food-quiche.png',
    customizations: ['Side Salad'],
  },
  {
    id: 'food-soup',
    name: 'Tomato Basil Soup',
    category: 'food',
    price: 5.50,
    description: 'Creamy tomato soup with fresh basil and a hint of garlic.',
    image: '/images/food/food-soup.png',
    customizations: ['Bread Bowl', 'Crackers'],
  },
  {
    id: 'food-wrap',
    name: 'Chicken Caesar Wrap',
    category: 'food',
    price: 8.75,
    description: 'Grilled chicken with romaine and Caesar dressing in a flour tortilla.',
    image: '/images/food/food-wrap.png',
    customizations: ['Gluten-Free Wrap', 'Extra Dressing'],
  },
];

export const getMenuByCategory = (category: string): MenuItem[] => {
  return menuItems.filter((item) => item.category === category);
};

export const getMenuItemById = (id: string): MenuItem | undefined => {
  return menuItems.find((item) => item.id === id);
};

export const categories = [
  { 
    id: 'coffee', 
    name: 'Coffee', 
    icon: 'Coffee',
    thumbnail: '/images/menu_thumbnail/coffee.png',
    color: 'from-amber-400 to-amber-600',
    description: 'Freshly brewed specialty coffee',
  },
  { 
    id: 'bakery', 
    name: 'Bakery', 
    icon: 'Croissant',
    thumbnail: '/images/menu_thumbnail/bakery.png',
    color: 'from-orange-400 to-orange-600',
    description: 'Baked fresh every morning',
  },
  { 
    id: 'cake', 
    name: 'Cake', 
    icon: 'Cake',
    thumbnail: '/images/menu_thumbnail/cake.png',
    color: 'from-pink-400 to-pink-600',
    description: 'Sweet treats and desserts',
  },
  { 
    id: 'food', 
    name: 'Food', 
    icon: 'UtensilsCrossed',
    thumbnail: '/images/menu_thumbnail/food.png',
    color: 'from-green-400 to-green-600',
    description: 'Light meals and salads',
  },
];
